### ISSUE TITLE
Creating new Payload for SignedJWT or JWSObject does not work

### ISSUE THREAD

**Issue by toniperello** [gesellix/Nimbus-JOSE-JWT#1]
Hi, i'm trying to make this example work:
             http://connect2id.com/products/nimbus-jose-jwt/examples/signed-and-encrypted-jwt
but i'm getting a NullPointerException at the part where i would encrypt my jweObject. From the looks of it, creating a new payload with SignedJWT or JWSObject doesn't return a valid Payload and has a "null" value which an NPE on JWEObject class at line 376.

Hope you hear from you soon.

Many thanks,
Toni

**Comment by gesellix** [comment]
Hi @toniperello this is only a fork of the original nimbus-jose-jwt library. Please open the issue at https://bitbucket.org/nimbusds/nimbus-jose-jwt
